# Generated by Django 3.1.5 on 2023-07-08 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20230708_1032'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kategorimodel',
            table='blog_kategorimodel',
        ),
    ]
