# Generated by Django 3.1.5 on 2023-07-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20230709_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yorummodel',
            name='guncellennme_tarihi',
        ),
        migrations.AddField(
            model_name='yorummodel',
            name='guncellenme_tarihi',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
